#!/bin/bash

# Fix SendGrid email tracking issue that causes redirects through url3965.everjust.com
# This script explains the issue and provides solutions

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}🔧 SendGrid Email Tracking Issue Analysis${NC}"
echo -e "${BLUE}=======================================${NC}"
echo ""

echo -e "${YELLOW}📋 PROBLEM IDENTIFIED:${NC}"
echo "The url3965.everjust.com domain appears in invitation emails because:"
echo "1. SendGrid automatically adds click tracking to all email links"
echo "2. This creates tracking URLs that redirect through SendGrid's servers"
echo "3. The tracking domain (url3965) is generated by SendGrid for your account"
echo ""

echo -e "${YELLOW}🔍 CURRENT STATUS:${NC}"
echo "✅ SSL certificate added for url3965.everjust.com"
echo "✅ DNS configured to point to our server"
echo "✅ Nginx configured to serve the domain"
echo "✅ Site URL set to https://everjust.chat"
echo ""

echo -e "${YELLOW}💡 SOLUTIONS IMPLEMENTED:${NC}"
echo "1. Changed MAIL_URL to use port 2525 (non-SSL) to avoid tracking"
echo "2. Ensured OVERWRITE_SETTING_Site_Url is correctly set"
echo "3. Added SSL certificate for the tracking domain"
echo ""

echo -e "${YELLOW}🎯 ADDITIONAL SOLUTIONS:${NC}"
echo ""
echo -e "${BLUE}Option 1: Disable SendGrid Click Tracking (Recommended)${NC}"
echo "- Log into SendGrid dashboard"
echo "- Go to Settings > Tracking"
echo "- Disable 'Click Tracking' globally"
echo "- This will prevent all tracking URLs"
echo ""

echo -e "${BLUE}Option 2: Configure Custom Link Branding${NC}"
echo "- In SendGrid dashboard, go to Settings > Sender Authentication"
echo "- Set up 'Link Branding' to use everjust.com instead of url3965.everjust.com"
echo "- This requires adding DNS records for link branding"
echo ""

echo -e "${BLUE}Option 3: Use Rocket.Chat's Built-in SMTP (Current)${NC}"
echo "- We've configured the system to use port 2525"
echo "- This should reduce tracking but may still occur"
echo ""

echo -e "${GREEN}✅ IMMEDIATE ACTIONS TAKEN:${NC}"
echo "1. Updated Docker Compose with correct SMTP settings"
echo "2. Restarted Rocket.Chat services"
echo "3. Ensured Site_Url is properly configured"
echo ""

echo -e "${YELLOW}📝 NEXT STEPS FOR USER:${NC}"
echo "1. Test new user invitations to see if tracking URLs still appear"
echo "2. If they do, disable click tracking in SendGrid dashboard"
echo "3. Alternatively, set up custom link branding in SendGrid"
echo ""

echo -e "${BLUE}🔗 SendGrid Dashboard Links:${NC}"
echo "- Tracking Settings: https://app.sendgrid.com/settings/tracking"
echo "- Sender Authentication: https://app.sendgrid.com/settings/sender_auth"
echo ""
