version: '3.8'

services:
  # Jitsi Meet Web Interface
  jitsi-web:
    image: jitsi/web:stable
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./jitsi-config/web:/config:Z
      - ./jitsi-config/web/letsencrypt:/etc/letsencrypt:Z
      - ./jitsi-config/transcripts:/usr/share/jitsi-meet/transcripts:Z
    environment:
      - ENABLE_LETSENCRYPT=0
      - ENABLE_HTTP_REDIRECT=0
      - DISABLE_HTTPS=1
      - LETSENCRYPT_DOMAIN=meet.everjust.com
      - LETSENCRYPT_EMAIL=support@everjust.com
      - PUBLIC_URL=https://meet.everjust.com
      - TZ=UTC
      - AMPLITUDE_ID
      - ANALYTICS_SCRIPT_URLS
      - ANALYTICS_WHITELISTED_EVENTS
      - BRIDGE_CHANNEL=web
      - BRANDING_DATA_URL
      - CALLSTATS_CUSTOM_SCRIPT_URL
      - CALLSTATS_ID
      - CALLSTATS_SECRET
      - CHROME_EXTENSION_BANNER_JSON
      - CONFCODE_URL
      - CONFIG_EXTERNAL_CONNECT
      - DEFAULT_LANGUAGE=en
      - DEPLOYMENTINFO_ENVIRONMENT
      - DEPLOYMENTINFO_ENVIRONMENT_TYPE
      - DEPLOYMENTINFO_USERREGION
      - DIALIN_NUMBERS_URL
      - DIALOUT_AUTH_URL
      - DIALOUT_CODES_URL
      - DROPBOX_APPKEY
      - DROPBOX_REDIRECT_URL
      - DYNAMIC_BRANDING_URL
      - ENABLE_AUDIO_PROCESSING
      - ENABLE_AUTH=0
      - ENABLE_CALENDAR
      - ENABLE_FILE_RECORDING_SERVICE
      - ENABLE_FILE_RECORDING_SERVICE_SHARING
      - ENABLE_GUESTS=1
      - ENABLE_IPV6
      - ENABLE_LIPSYNC
      - ENABLE_NO_AUDIO_DETECTION
      - ENABLE_P2P
      - ENABLE_PREJOIN_PAGE
      - ENABLE_WELCOME_PAGE
      - ENABLE_CLOSE_PAGE
      - ENABLE_RECORDING
      # Hide Jitsi branding and logos
      - SHOW_JITSI_WATERMARK=false
      - SHOW_WATERMARK_FOR_GUESTS=false
      - SHOW_BRAND_WATERMARK=false
      - BRAND_WATERMARK_LINK=""
      - JITSI_WATERMARK_LINK=""
      - DEFAULT_LOGO_URL=""
      - DEFAULT_WELCOME_PAGE_LOGO_URL=""
      # Custom branding for EVERJUST
      - APP_NAME="EVERJUST MEET"
      - NATIVE_APP_NAME="EVERJUST MEET"
      - PROVIDER_NAME="EVERJUST"
      # Custom Open Graph meta tags for invite previews
      - OG_TITLE="EVERJUST Video Call"
      - OG_DESCRIPTION="Join secure, high-quality video meetings with EVERJUST. Connect instantly with crystal-clear audio and video."
      - OG_IMAGE="https://meet.everjust.com/images/everjust-meeting-preview.png"
      - OG_SITE_NAME="EVERJUST"
      # Custom logo URLs
      - DEFAULT_LOGO_URL="images/everjust-logo.png"
      - DEFAULT_WELCOME_PAGE_LOGO_URL="images/everjust-logo.png"
      - HIDE_INVITE_MORE_HEADER=true
      - ENABLE_REMB
      - ENABLE_REQUIRE_DISPLAY_NAME
      - ENABLE_SIMULCAST
      - ENABLE_STATS_ID
      - ENABLE_STEREO
      - ENABLE_SUBDOMAINS
      - ENABLE_TALK_WHILE_MUTED
      - ENABLE_TCC
      - ENABLE_TRANSCRIPTIONS
      - ETHERPAD_PUBLIC_URL
      - ETHERPAD_URL_BASE
      - GOOGLE_ANALYTICS_ID
      - GOOGLE_API_APP_ID
      - HIDE_PREMEETING_BUTTONS
      - INVITE_SERVICE_URL
      - MATOMO_ENDPOINT
      - MATOMO_SITE_ID
      - MICROSOFT_API_APP_ID
      - NGINX_RESOLVER
      - NGINX_WORKER_CONNECTIONS
      - NGINX_WORKER_PROCESSES
      - PEOPLE_SEARCH_URL
      - RESOLUTION
      - RESOLUTION_MIN
      - RESOLUTION_WIDTH
      - RESOLUTION_WIDTH_MIN
      - START_AUDIO_ONLY
      - START_AUDIO_MUTED
      - START_WITH_AUDIO_MUTED
      - START_SILENT
      - DISABLE_AUDIO_LEVELS
      - ENABLE_NOISY_MIC_DETECTION
      - START_BITRATE
      - DESKTOP_SHARING_FRAMERATE_MIN
      - DESKTOP_SHARING_FRAMERATE_MAX
      - START_VIDEO_MUTED
      - START_WITH_VIDEO_MUTED
      - TESTING_CAP_SCREENSHARE_BITRATE
      - TESTING_OCTO_PROBABILITY
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_BOSH_URL_BASE=http://jitsi-prosody:5280
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_GUEST_DOMAIN=guest.meet.jitsi
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - XMPP_RECORDER_DOMAIN=recorder.meet.jitsi
    depends_on:
      - jitsi-prosody
    networks:
      - jitsi-meet

  # Jitsi Video Bridge
  jitsi-jvb:
    image: jitsi/jvb:stable
    restart: unless-stopped
    ports:
      - "10000:10000/udp"
      - "4443:4443"
    volumes:
      - ./jitsi-config/jvb:/config:Z
    environment:
      - DOCKER_HOST_ADDRESS=159.65.185.227
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_SERVER=jitsi-prosody
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=EverJust2025!
      - JVB_ENABLE_APIS=rest,colibri
      - JVB_STUN_SERVERS=meet-jit-si-turnrelay.jitsi.net:443
      - JVB_PORT=10000
      - JVB_TCP_HARVESTER_DISABLED=true
      - JVB_TCP_PORT=4443
      - JVB_TCP_MAPPED_PORT=4443
      - JVB_BREWERY_MUC=jvbbrewery
      - COLIBRI_REST_ENABLED=true
      - SHUTDOWN_REST_ENABLED=true
      - TZ=UTC
    depends_on:
      - jitsi-prosody
    networks:
      - jitsi-meet

  # Jitsi Conference Focus
  jitsi-jicofo:
    image: jitsi/jicofo:stable
    restart: unless-stopped
    volumes:
      - ./jitsi-config/jicofo:/config:Z
    environment:
      - ENABLE_AUTH=0
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - XMPP_SERVER=jitsi-prosody
      - JICOFO_COMPONENT_SECRET=s3cr3t
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=EverJust2025!
      - JVB_BREWERY_MUC=jvbbrewery
      - JIGASI_BREWERY_MUC=jigasibrewery
      - JIGASI_SIP_URI=test@sip2sip.info
      - TZ=UTC
    depends_on:
      - jitsi-prosody
    networks:
      - jitsi-meet

  # Jitsi Prosody XMPP Server
  jitsi-prosody:
    image: jitsi/prosody:stable
    restart: unless-stopped
    expose:
      - "5222"
      - "5347"
      - "5280"
    volumes:
      - ./jitsi-config/prosody/config:/config:Z
      - ./jitsi-config/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
    environment:
      - AUTH_TYPE=anonymous
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - GLOBAL_MODULES
      - GLOBAL_CONFIG
      - LDAP_URL
      - LDAP_BASE
      - LDAP_BINDDN
      - LDAP_BINDPW
      - LDAP_FILTER
      - LDAP_AUTH_METHOD
      - LDAP_VERSION
      - LDAP_USE_TLS
      - LDAP_TLS_CIPHERS
      - LDAP_TLS_CHECK_PEER
      - LDAP_TLS_CACERT_FILE
      - LDAP_TLS_CACERT_DIR
      - LDAP_START_TLS
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_GUEST_DOMAIN=guest.meet.jitsi
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_MODULES
      - XMPP_MUC_MODULES
      - XMPP_INTERNAL_MUC_MODULES
      - XMPP_RECORDER_DOMAIN=recorder.meet.jitsi
      - JICOFO_COMPONENT_SECRET=s3cr3t
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=EverJust2025!
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=EverJust2025!
      - TZ=UTC
      - PUBLIC_URL=https://meet.everjust.com
    networks:
      - jitsi-meet

networks:
  jitsi-meet:
    driver: bridge
